// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: INS_MESSAGE_KR_TW.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type INS_MESSAGE_KR_TW struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Time          *uint32                `protobuf:"varint,2,req,name=time" json:"time,omitempty"`
	Text          *string                `protobuf:"bytes,3,req,name=text" json:"text,omitempty"`
	Picture       *string                `protobuf:"bytes,4,opt,name=picture" json:"picture,omitempty"`
	PlayerDiscuss []*INS_PLAYER_KR_TW    `protobuf:"bytes,5,rep,name=player_discuss,json=playerDiscuss" json:"player_discuss,omitempty"`
	NpcDiscuss    []*INS_NPC             `protobuf:"bytes,6,rep,name=npc_discuss,json=npcDiscuss" json:"npc_discuss,omitempty"`
	NpcReply      []*INS_NPC             `protobuf:"bytes,7,rep,name=npc_reply,json=npcReply" json:"npc_reply,omitempty"`
	Good          *uint32                `protobuf:"varint,8,req,name=good" json:"good,omitempty"`
	IsGood        *uint32                `protobuf:"varint,9,req,name=is_good,json=isGood" json:"is_good,omitempty"`
	IsRead        *uint32                `protobuf:"varint,10,req,name=is_read,json=isRead" json:"is_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INS_MESSAGE_KR_TW) Reset() {
	*x = INS_MESSAGE_KR_TW{}
	mi := &file_INS_MESSAGE_KR_TW_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INS_MESSAGE_KR_TW) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INS_MESSAGE_KR_TW) ProtoMessage() {}

func (x *INS_MESSAGE_KR_TW) ProtoReflect() protoreflect.Message {
	mi := &file_INS_MESSAGE_KR_TW_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INS_MESSAGE_KR_TW.ProtoReflect.Descriptor instead.
func (*INS_MESSAGE_KR_TW) Descriptor() ([]byte, []int) {
	return file_INS_MESSAGE_KR_TW_proto_rawDescGZIP(), []int{0}
}

func (x *INS_MESSAGE_KR_TW) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *INS_MESSAGE_KR_TW) GetTime() uint32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

func (x *INS_MESSAGE_KR_TW) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *INS_MESSAGE_KR_TW) GetPicture() string {
	if x != nil && x.Picture != nil {
		return *x.Picture
	}
	return ""
}

func (x *INS_MESSAGE_KR_TW) GetPlayerDiscuss() []*INS_PLAYER_KR_TW {
	if x != nil {
		return x.PlayerDiscuss
	}
	return nil
}

func (x *INS_MESSAGE_KR_TW) GetNpcDiscuss() []*INS_NPC {
	if x != nil {
		return x.NpcDiscuss
	}
	return nil
}

func (x *INS_MESSAGE_KR_TW) GetNpcReply() []*INS_NPC {
	if x != nil {
		return x.NpcReply
	}
	return nil
}

func (x *INS_MESSAGE_KR_TW) GetGood() uint32 {
	if x != nil && x.Good != nil {
		return *x.Good
	}
	return 0
}

func (x *INS_MESSAGE_KR_TW) GetIsGood() uint32 {
	if x != nil && x.IsGood != nil {
		return *x.IsGood
	}
	return 0
}

func (x *INS_MESSAGE_KR_TW) GetIsRead() uint32 {
	if x != nil && x.IsRead != nil {
		return *x.IsRead
	}
	return 0
}

var File_INS_MESSAGE_KR_TW_proto protoreflect.FileDescriptor

const file_INS_MESSAGE_KR_TW_proto_rawDesc = "" +
	"\n" +
	"\x17INS_MESSAGE_KR_TW.proto\x12\abelfast\x1a\rINS_NPC.proto\x1a\x16INS_PLAYER_KR_TW.proto\"\xcf\x02\n" +
	"\x11INS_MESSAGE_KR_TW\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x12\n" +
	"\x04time\x18\x02 \x02(\rR\x04time\x12\x12\n" +
	"\x04text\x18\x03 \x02(\tR\x04text\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\x12@\n" +
	"\x0eplayer_discuss\x18\x05 \x03(\v2\x19.belfast.INS_PLAYER_KR_TWR\rplayerDiscuss\x121\n" +
	"\vnpc_discuss\x18\x06 \x03(\v2\x10.belfast.INS_NPCR\n" +
	"npcDiscuss\x12-\n" +
	"\tnpc_reply\x18\a \x03(\v2\x10.belfast.INS_NPCR\bnpcReply\x12\x12\n" +
	"\x04good\x18\b \x02(\rR\x04good\x12\x17\n" +
	"\ais_good\x18\t \x02(\rR\x06isGood\x12\x17\n" +
	"\ais_read\x18\n" +
	" \x02(\rR\x06isReadB\fZ\n" +
	"./protobuf"

var (
	file_INS_MESSAGE_KR_TW_proto_rawDescOnce sync.Once
	file_INS_MESSAGE_KR_TW_proto_rawDescData []byte
)

func file_INS_MESSAGE_KR_TW_proto_rawDescGZIP() []byte {
	file_INS_MESSAGE_KR_TW_proto_rawDescOnce.Do(func() {
		file_INS_MESSAGE_KR_TW_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_INS_MESSAGE_KR_TW_proto_rawDesc), len(file_INS_MESSAGE_KR_TW_proto_rawDesc)))
	})
	return file_INS_MESSAGE_KR_TW_proto_rawDescData
}

var file_INS_MESSAGE_KR_TW_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_INS_MESSAGE_KR_TW_proto_goTypes = []any{
	(*INS_MESSAGE_KR_TW)(nil), // 0: belfast.INS_MESSAGE_KR_TW
	(*INS_PLAYER_KR_TW)(nil),  // 1: belfast.INS_PLAYER_KR_TW
	(*INS_NPC)(nil),           // 2: belfast.INS_NPC
}
var file_INS_MESSAGE_KR_TW_proto_depIdxs = []int32{
	1, // 0: belfast.INS_MESSAGE_KR_TW.player_discuss:type_name -> belfast.INS_PLAYER_KR_TW
	2, // 1: belfast.INS_MESSAGE_KR_TW.npc_discuss:type_name -> belfast.INS_NPC
	2, // 2: belfast.INS_MESSAGE_KR_TW.npc_reply:type_name -> belfast.INS_NPC
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_INS_MESSAGE_KR_TW_proto_init() }
func file_INS_MESSAGE_KR_TW_proto_init() {
	if File_INS_MESSAGE_KR_TW_proto != nil {
		return
	}
	file_INS_NPC_proto_init()
	file_INS_PLAYER_KR_TW_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_INS_MESSAGE_KR_TW_proto_rawDesc), len(file_INS_MESSAGE_KR_TW_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_INS_MESSAGE_KR_TW_proto_goTypes,
		DependencyIndexes: file_INS_MESSAGE_KR_TW_proto_depIdxs,
		MessageInfos:      file_INS_MESSAGE_KR_TW_proto_msgTypes,
	}.Build()
	File_INS_MESSAGE_KR_TW_proto = out.File
	file_INS_MESSAGE_KR_TW_proto_goTypes = nil
	file_INS_MESSAGE_KR_TW_proto_depIdxs = nil
}
