// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: SC_21540.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SC_21540 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *uint32                `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	DropList      []*DROPINFO            `protobuf:"bytes,2,rep,name=drop_list,json=dropList" json:"drop_list,omitempty"`
	ShipList      []*PB_GATHER_SHIP      `protobuf:"bytes,3,rep,name=ship_list,json=shipList" json:"ship_list,omitempty"`
	GatherList    []uint32               `protobuf:"varint,4,rep,name=gather_list,json=gatherList" json:"gather_list,omitempty"`
	BuildRefresh  []*PB_BUILD_REFRESH    `protobuf:"bytes,5,rep,name=build_refresh,json=buildRefresh" json:"build_refresh,omitempty"`
	CostGold      *uint32                `protobuf:"varint,6,req,name=cost_gold,json=costGold" json:"cost_gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_21540) Reset() {
	*x = SC_21540{}
	mi := &file_SC_21540_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_21540) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_21540) ProtoMessage() {}

func (x *SC_21540) ProtoReflect() protoreflect.Message {
	mi := &file_SC_21540_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_21540.ProtoReflect.Descriptor instead.
func (*SC_21540) Descriptor() ([]byte, []int) {
	return file_SC_21540_proto_rawDescGZIP(), []int{0}
}

func (x *SC_21540) GetResult() uint32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *SC_21540) GetDropList() []*DROPINFO {
	if x != nil {
		return x.DropList
	}
	return nil
}

func (x *SC_21540) GetShipList() []*PB_GATHER_SHIP {
	if x != nil {
		return x.ShipList
	}
	return nil
}

func (x *SC_21540) GetGatherList() []uint32 {
	if x != nil {
		return x.GatherList
	}
	return nil
}

func (x *SC_21540) GetBuildRefresh() []*PB_BUILD_REFRESH {
	if x != nil {
		return x.BuildRefresh
	}
	return nil
}

func (x *SC_21540) GetCostGold() uint32 {
	if x != nil && x.CostGold != nil {
		return *x.CostGold
	}
	return 0
}

var File_SC_21540_proto protoreflect.FileDescriptor

const file_SC_21540_proto_rawDesc = "" +
	"\n" +
	"\x0eSC_21540.proto\x12\abelfast\x1a\x0eDROPINFO.proto\x1a\x16PB_BUILD_REFRESH.proto\x1a\x14PB_GATHER_SHIP.proto\"\x86\x02\n" +
	"\bSC_21540\x12\x16\n" +
	"\x06result\x18\x01 \x02(\rR\x06result\x12.\n" +
	"\tdrop_list\x18\x02 \x03(\v2\x11.belfast.DROPINFOR\bdropList\x124\n" +
	"\tship_list\x18\x03 \x03(\v2\x17.belfast.PB_GATHER_SHIPR\bshipList\x12\x1f\n" +
	"\vgather_list\x18\x04 \x03(\rR\n" +
	"gatherList\x12>\n" +
	"\rbuild_refresh\x18\x05 \x03(\v2\x19.belfast.PB_BUILD_REFRESHR\fbuildRefresh\x12\x1b\n" +
	"\tcost_gold\x18\x06 \x02(\rR\bcostGoldB\fZ\n" +
	"./protobuf"

var (
	file_SC_21540_proto_rawDescOnce sync.Once
	file_SC_21540_proto_rawDescData []byte
)

func file_SC_21540_proto_rawDescGZIP() []byte {
	file_SC_21540_proto_rawDescOnce.Do(func() {
		file_SC_21540_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SC_21540_proto_rawDesc), len(file_SC_21540_proto_rawDesc)))
	})
	return file_SC_21540_proto_rawDescData
}

var file_SC_21540_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SC_21540_proto_goTypes = []any{
	(*SC_21540)(nil),         // 0: belfast.SC_21540
	(*DROPINFO)(nil),         // 1: belfast.DROPINFO
	(*PB_GATHER_SHIP)(nil),   // 2: belfast.PB_GATHER_SHIP
	(*PB_BUILD_REFRESH)(nil), // 3: belfast.PB_BUILD_REFRESH
}
var file_SC_21540_proto_depIdxs = []int32{
	1, // 0: belfast.SC_21540.drop_list:type_name -> belfast.DROPINFO
	2, // 1: belfast.SC_21540.ship_list:type_name -> belfast.PB_GATHER_SHIP
	3, // 2: belfast.SC_21540.build_refresh:type_name -> belfast.PB_BUILD_REFRESH
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_SC_21540_proto_init() }
func file_SC_21540_proto_init() {
	if File_SC_21540_proto != nil {
		return
	}
	file_DROPINFO_proto_init()
	file_PB_BUILD_REFRESH_proto_init()
	file_PB_GATHER_SHIP_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SC_21540_proto_rawDesc), len(file_SC_21540_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SC_21540_proto_goTypes,
		DependencyIndexes: file_SC_21540_proto_depIdxs,
		MessageInfos:      file_SC_21540_proto_msgTypes,
	}.Build()
	File_SC_21540_proto = out.File
	file_SC_21540_proto_goTypes = nil
	file_SC_21540_proto_depIdxs = nil
}
