// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: TBBENEFITVAL.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TBBENEFITVAL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buffid        *uint32                `protobuf:"varint,1,req,name=buffid" json:"buffid,omitempty"`
	Benefitval    []*KVDATA              `protobuf:"bytes,2,rep,name=benefitval" json:"benefitval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TBBENEFITVAL) Reset() {
	*x = TBBENEFITVAL{}
	mi := &file_TBBENEFITVAL_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TBBENEFITVAL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TBBENEFITVAL) ProtoMessage() {}

func (x *TBBENEFITVAL) ProtoReflect() protoreflect.Message {
	mi := &file_TBBENEFITVAL_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TBBENEFITVAL.ProtoReflect.Descriptor instead.
func (*TBBENEFITVAL) Descriptor() ([]byte, []int) {
	return file_TBBENEFITVAL_proto_rawDescGZIP(), []int{0}
}

func (x *TBBENEFITVAL) GetBuffid() uint32 {
	if x != nil && x.Buffid != nil {
		return *x.Buffid
	}
	return 0
}

func (x *TBBENEFITVAL) GetBenefitval() []*KVDATA {
	if x != nil {
		return x.Benefitval
	}
	return nil
}

var File_TBBENEFITVAL_proto protoreflect.FileDescriptor

const file_TBBENEFITVAL_proto_rawDesc = "" +
	"\n" +
	"\x12TBBENEFITVAL.proto\x12\abelfast\x1a\fKVDATA.proto\"W\n" +
	"\fTBBENEFITVAL\x12\x16\n" +
	"\x06buffid\x18\x01 \x02(\rR\x06buffid\x12/\n" +
	"\n" +
	"benefitval\x18\x02 \x03(\v2\x0f.belfast.KVDATAR\n" +
	"benefitvalB\fZ\n" +
	"./protobuf"

var (
	file_TBBENEFITVAL_proto_rawDescOnce sync.Once
	file_TBBENEFITVAL_proto_rawDescData []byte
)

func file_TBBENEFITVAL_proto_rawDescGZIP() []byte {
	file_TBBENEFITVAL_proto_rawDescOnce.Do(func() {
		file_TBBENEFITVAL_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TBBENEFITVAL_proto_rawDesc), len(file_TBBENEFITVAL_proto_rawDesc)))
	})
	return file_TBBENEFITVAL_proto_rawDescData
}

var file_TBBENEFITVAL_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TBBENEFITVAL_proto_goTypes = []any{
	(*TBBENEFITVAL)(nil), // 0: belfast.TBBENEFITVAL
	(*KVDATA)(nil),       // 1: belfast.KVDATA
}
var file_TBBENEFITVAL_proto_depIdxs = []int32{
	1, // 0: belfast.TBBENEFITVAL.benefitval:type_name -> belfast.KVDATA
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_TBBENEFITVAL_proto_init() }
func file_TBBENEFITVAL_proto_init() {
	if File_TBBENEFITVAL_proto != nil {
		return
	}
	file_KVDATA_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TBBENEFITVAL_proto_rawDesc), len(file_TBBENEFITVAL_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TBBENEFITVAL_proto_goTypes,
		DependencyIndexes: file_TBBENEFITVAL_proto_depIdxs,
		MessageInfos:      file_TBBENEFITVAL_proto_msgTypes,
	}.Build()
	File_TBBENEFITVAL_proto = out.File
	file_TBBENEFITVAL_proto_goTypes = nil
	file_TBBENEFITVAL_proto_depIdxs = nil
}
