// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: TBBFCHANGE.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TBBFCHANGE struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DropType        *uint32                `protobuf:"varint,1,req,name=drop_type,json=dropType" json:"drop_type,omitempty"`
	DropId          *uint32                `protobuf:"varint,2,req,name=drop_id,json=dropId" json:"drop_id,omitempty"`
	PositiveCounter *uint32                `protobuf:"varint,3,req,name=positive_counter,json=positiveCounter" json:"positive_counter,omitempty"`
	NegativeCounter *uint32                `protobuf:"varint,4,req,name=negative_counter,json=negativeCounter" json:"negative_counter,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TBBFCHANGE) Reset() {
	*x = TBBFCHANGE{}
	mi := &file_TBBFCHANGE_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TBBFCHANGE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TBBFCHANGE) ProtoMessage() {}

func (x *TBBFCHANGE) ProtoReflect() protoreflect.Message {
	mi := &file_TBBFCHANGE_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TBBFCHANGE.ProtoReflect.Descriptor instead.
func (*TBBFCHANGE) Descriptor() ([]byte, []int) {
	return file_TBBFCHANGE_proto_rawDescGZIP(), []int{0}
}

func (x *TBBFCHANGE) GetDropType() uint32 {
	if x != nil && x.DropType != nil {
		return *x.DropType
	}
	return 0
}

func (x *TBBFCHANGE) GetDropId() uint32 {
	if x != nil && x.DropId != nil {
		return *x.DropId
	}
	return 0
}

func (x *TBBFCHANGE) GetPositiveCounter() uint32 {
	if x != nil && x.PositiveCounter != nil {
		return *x.PositiveCounter
	}
	return 0
}

func (x *TBBFCHANGE) GetNegativeCounter() uint32 {
	if x != nil && x.NegativeCounter != nil {
		return *x.NegativeCounter
	}
	return 0
}

var File_TBBFCHANGE_proto protoreflect.FileDescriptor

const file_TBBFCHANGE_proto_rawDesc = "" +
	"\n" +
	"\x10TBBFCHANGE.proto\x12\abelfast\"\x98\x01\n" +
	"\n" +
	"TBBFCHANGE\x12\x1b\n" +
	"\tdrop_type\x18\x01 \x02(\rR\bdropType\x12\x17\n" +
	"\adrop_id\x18\x02 \x02(\rR\x06dropId\x12)\n" +
	"\x10positive_counter\x18\x03 \x02(\rR\x0fpositiveCounter\x12)\n" +
	"\x10negative_counter\x18\x04 \x02(\rR\x0fnegativeCounterB\fZ\n" +
	"./protobuf"

var (
	file_TBBFCHANGE_proto_rawDescOnce sync.Once
	file_TBBFCHANGE_proto_rawDescData []byte
)

func file_TBBFCHANGE_proto_rawDescGZIP() []byte {
	file_TBBFCHANGE_proto_rawDescOnce.Do(func() {
		file_TBBFCHANGE_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TBBFCHANGE_proto_rawDesc), len(file_TBBFCHANGE_proto_rawDesc)))
	})
	return file_TBBFCHANGE_proto_rawDescData
}

var file_TBBFCHANGE_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TBBFCHANGE_proto_goTypes = []any{
	(*TBBFCHANGE)(nil), // 0: belfast.TBBFCHANGE
}
var file_TBBFCHANGE_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TBBFCHANGE_proto_init() }
func file_TBBFCHANGE_proto_init() {
	if File_TBBFCHANGE_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TBBFCHANGE_proto_rawDesc), len(file_TBBFCHANGE_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TBBFCHANGE_proto_goTypes,
		DependencyIndexes: file_TBBFCHANGE_proto_depIdxs,
		MessageInfos:      file_TBBFCHANGE_proto_msgTypes,
	}.Build()
	File_TBBFCHANGE_proto = out.File
	file_TBBFCHANGE_proto_goTypes = nil
	file_TBBFCHANGE_proto_depIdxs = nil
}
