// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: TBBFCOUNTER.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TBBFCOUNTER struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *uint32                `protobuf:"varint,1,req,name=group" json:"group,omitempty"`
	Change        []*TBBFCHANGE          `protobuf:"bytes,2,rep,name=change" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TBBFCOUNTER) Reset() {
	*x = TBBFCOUNTER{}
	mi := &file_TBBFCOUNTER_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TBBFCOUNTER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TBBFCOUNTER) ProtoMessage() {}

func (x *TBBFCOUNTER) ProtoReflect() protoreflect.Message {
	mi := &file_TBBFCOUNTER_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TBBFCOUNTER.ProtoReflect.Descriptor instead.
func (*TBBFCOUNTER) Descriptor() ([]byte, []int) {
	return file_TBBFCOUNTER_proto_rawDescGZIP(), []int{0}
}

func (x *TBBFCOUNTER) GetGroup() uint32 {
	if x != nil && x.Group != nil {
		return *x.Group
	}
	return 0
}

func (x *TBBFCOUNTER) GetChange() []*TBBFCHANGE {
	if x != nil {
		return x.Change
	}
	return nil
}

var File_TBBFCOUNTER_proto protoreflect.FileDescriptor

const file_TBBFCOUNTER_proto_rawDesc = "" +
	"\n" +
	"\x11TBBFCOUNTER.proto\x12\abelfast\x1a\x10TBBFCHANGE.proto\"P\n" +
	"\vTBBFCOUNTER\x12\x14\n" +
	"\x05group\x18\x01 \x02(\rR\x05group\x12+\n" +
	"\x06change\x18\x02 \x03(\v2\x13.belfast.TBBFCHANGER\x06changeB\fZ\n" +
	"./protobuf"

var (
	file_TBBFCOUNTER_proto_rawDescOnce sync.Once
	file_TBBFCOUNTER_proto_rawDescData []byte
)

func file_TBBFCOUNTER_proto_rawDescGZIP() []byte {
	file_TBBFCOUNTER_proto_rawDescOnce.Do(func() {
		file_TBBFCOUNTER_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TBBFCOUNTER_proto_rawDesc), len(file_TBBFCOUNTER_proto_rawDesc)))
	})
	return file_TBBFCOUNTER_proto_rawDescData
}

var file_TBBFCOUNTER_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TBBFCOUNTER_proto_goTypes = []any{
	(*TBBFCOUNTER)(nil), // 0: belfast.TBBFCOUNTER
	(*TBBFCHANGE)(nil),  // 1: belfast.TBBFCHANGE
}
var file_TBBFCOUNTER_proto_depIdxs = []int32{
	1, // 0: belfast.TBBFCOUNTER.change:type_name -> belfast.TBBFCHANGE
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_TBBFCOUNTER_proto_init() }
func file_TBBFCOUNTER_proto_init() {
	if File_TBBFCOUNTER_proto != nil {
		return
	}
	file_TBBFCHANGE_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TBBFCOUNTER_proto_rawDesc), len(file_TBBFCOUNTER_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TBBFCOUNTER_proto_goTypes,
		DependencyIndexes: file_TBBFCOUNTER_proto_depIdxs,
		MessageInfos:      file_TBBFCOUNTER_proto_msgTypes,
	}.Build()
	File_TBBFCOUNTER_proto = out.File
	file_TBBFCOUNTER_proto_goTypes = nil
	file_TBBFCOUNTER_proto_depIdxs = nil
}
