// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: TBDISPLAY.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TBDISPLAY struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BenefitDisplay   []*TBDROP              `protobuf:"bytes,1,rep,name=benefit_display,json=benefitDisplay" json:"benefit_display,omitempty"`
	DollarNumDisplay []*TBBENEFITVAL        `protobuf:"bytes,2,rep,name=dollar_num_display,json=dollarNumDisplay" json:"dollar_num_display,omitempty"`
	Counter          []*TBBFCOUNTER         `protobuf:"bytes,3,rep,name=counter" json:"counter,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TBDISPLAY) Reset() {
	*x = TBDISPLAY{}
	mi := &file_TBDISPLAY_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TBDISPLAY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TBDISPLAY) ProtoMessage() {}

func (x *TBDISPLAY) ProtoReflect() protoreflect.Message {
	mi := &file_TBDISPLAY_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TBDISPLAY.ProtoReflect.Descriptor instead.
func (*TBDISPLAY) Descriptor() ([]byte, []int) {
	return file_TBDISPLAY_proto_rawDescGZIP(), []int{0}
}

func (x *TBDISPLAY) GetBenefitDisplay() []*TBDROP {
	if x != nil {
		return x.BenefitDisplay
	}
	return nil
}

func (x *TBDISPLAY) GetDollarNumDisplay() []*TBBENEFITVAL {
	if x != nil {
		return x.DollarNumDisplay
	}
	return nil
}

func (x *TBDISPLAY) GetCounter() []*TBBFCOUNTER {
	if x != nil {
		return x.Counter
	}
	return nil
}

var File_TBDISPLAY_proto protoreflect.FileDescriptor

const file_TBDISPLAY_proto_rawDesc = "" +
	"\n" +
	"\x0fTBDISPLAY.proto\x12\abelfast\x1a\x12TBBENEFITVAL.proto\x1a\x11TBBFCOUNTER.proto\x1a\fTBDROP.proto\"\xba\x01\n" +
	"\tTBDISPLAY\x128\n" +
	"\x0fbenefit_display\x18\x01 \x03(\v2\x0f.belfast.TBDROPR\x0ebenefitDisplay\x12C\n" +
	"\x12dollar_num_display\x18\x02 \x03(\v2\x15.belfast.TBBENEFITVALR\x10dollarNumDisplay\x12.\n" +
	"\acounter\x18\x03 \x03(\v2\x14.belfast.TBBFCOUNTERR\acounterB\fZ\n" +
	"./protobuf"

var (
	file_TBDISPLAY_proto_rawDescOnce sync.Once
	file_TBDISPLAY_proto_rawDescData []byte
)

func file_TBDISPLAY_proto_rawDescGZIP() []byte {
	file_TBDISPLAY_proto_rawDescOnce.Do(func() {
		file_TBDISPLAY_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TBDISPLAY_proto_rawDesc), len(file_TBDISPLAY_proto_rawDesc)))
	})
	return file_TBDISPLAY_proto_rawDescData
}

var file_TBDISPLAY_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TBDISPLAY_proto_goTypes = []any{
	(*TBDISPLAY)(nil),    // 0: belfast.TBDISPLAY
	(*TBDROP)(nil),       // 1: belfast.TBDROP
	(*TBBENEFITVAL)(nil), // 2: belfast.TBBENEFITVAL
	(*TBBFCOUNTER)(nil),  // 3: belfast.TBBFCOUNTER
}
var file_TBDISPLAY_proto_depIdxs = []int32{
	1, // 0: belfast.TBDISPLAY.benefit_display:type_name -> belfast.TBDROP
	2, // 1: belfast.TBDISPLAY.dollar_num_display:type_name -> belfast.TBBENEFITVAL
	3, // 2: belfast.TBDISPLAY.counter:type_name -> belfast.TBBFCOUNTER
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_TBDISPLAY_proto_init() }
func file_TBDISPLAY_proto_init() {
	if File_TBDISPLAY_proto != nil {
		return
	}
	file_TBBENEFITVAL_proto_init()
	file_TBBFCOUNTER_proto_init()
	file_TBDROP_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TBDISPLAY_proto_rawDesc), len(file_TBDISPLAY_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TBDISPLAY_proto_goTypes,
		DependencyIndexes: file_TBDISPLAY_proto_depIdxs,
		MessageInfos:      file_TBDISPLAY_proto_msgTypes,
	}.Build()
	File_TBDISPLAY_proto = out.File
	file_TBDISPLAY_proto_goTypes = nil
	file_TBDISPLAY_proto_depIdxs = nil
}
