// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: TBDROPS_KR.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TBDROPS_KR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseDrop      []*TBDROP              `protobuf:"bytes,1,rep,name=base_drop,json=baseDrop" json:"base_drop,omitempty"`
	BenefitDrop   []*TBDROP              `protobuf:"bytes,2,rep,name=benefit_drop,json=benefitDrop" json:"benefit_drop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TBDROPS_KR) Reset() {
	*x = TBDROPS_KR{}
	mi := &file_TBDROPS_KR_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TBDROPS_KR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TBDROPS_KR) ProtoMessage() {}

func (x *TBDROPS_KR) ProtoReflect() protoreflect.Message {
	mi := &file_TBDROPS_KR_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TBDROPS_KR.ProtoReflect.Descriptor instead.
func (*TBDROPS_KR) Descriptor() ([]byte, []int) {
	return file_TBDROPS_KR_proto_rawDescGZIP(), []int{0}
}

func (x *TBDROPS_KR) GetBaseDrop() []*TBDROP {
	if x != nil {
		return x.BaseDrop
	}
	return nil
}

func (x *TBDROPS_KR) GetBenefitDrop() []*TBDROP {
	if x != nil {
		return x.BenefitDrop
	}
	return nil
}

var File_TBDROPS_KR_proto protoreflect.FileDescriptor

const file_TBDROPS_KR_proto_rawDesc = "" +
	"\n" +
	"\x10TBDROPS_KR.proto\x12\abelfast\x1a\fTBDROP.proto\"n\n" +
	"\n" +
	"TBDROPS_KR\x12,\n" +
	"\tbase_drop\x18\x01 \x03(\v2\x0f.belfast.TBDROPR\bbaseDrop\x122\n" +
	"\fbenefit_drop\x18\x02 \x03(\v2\x0f.belfast.TBDROPR\vbenefitDropB\fZ\n" +
	"./protobuf"

var (
	file_TBDROPS_KR_proto_rawDescOnce sync.Once
	file_TBDROPS_KR_proto_rawDescData []byte
)

func file_TBDROPS_KR_proto_rawDescGZIP() []byte {
	file_TBDROPS_KR_proto_rawDescOnce.Do(func() {
		file_TBDROPS_KR_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TBDROPS_KR_proto_rawDesc), len(file_TBDROPS_KR_proto_rawDesc)))
	})
	return file_TBDROPS_KR_proto_rawDescData
}

var file_TBDROPS_KR_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TBDROPS_KR_proto_goTypes = []any{
	(*TBDROPS_KR)(nil), // 0: belfast.TBDROPS_KR
	(*TBDROP)(nil),     // 1: belfast.TBDROP
}
var file_TBDROPS_KR_proto_depIdxs = []int32{
	1, // 0: belfast.TBDROPS_KR.base_drop:type_name -> belfast.TBDROP
	1, // 1: belfast.TBDROPS_KR.benefit_drop:type_name -> belfast.TBDROP
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_TBDROPS_KR_proto_init() }
func file_TBDROPS_KR_proto_init() {
	if File_TBDROPS_KR_proto != nil {
		return
	}
	file_TBDROP_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TBDROPS_KR_proto_rawDesc), len(file_TBDROPS_KR_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TBDROPS_KR_proto_goTypes,
		DependencyIndexes: file_TBDROPS_KR_proto_depIdxs,
		MessageInfos:      file_TBDROPS_KR_proto_msgTypes,
	}.Build()
	File_TBDROPS_KR_proto = out.File
	file_TBDROPS_KR_proto_goTypes = nil
	file_TBDROPS_KR_proto_depIdxs = nil
}
