// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: TBFSMCACHENIN1.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TBFSMCACHENIN1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selects       []*TBDROP              `protobuf:"bytes,1,rep,name=selects" json:"selects,omitempty"`
	RerollCount   []uint32               `protobuf:"varint,2,rep,name=reroll_count,json=rerollCount" json:"reroll_count,omitempty"`
	IsFromShop    *uint32                `protobuf:"varint,3,req,name=is_from_shop,json=isFromShop" json:"is_from_shop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TBFSMCACHENIN1) Reset() {
	*x = TBFSMCACHENIN1{}
	mi := &file_TBFSMCACHENIN1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TBFSMCACHENIN1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TBFSMCACHENIN1) ProtoMessage() {}

func (x *TBFSMCACHENIN1) ProtoReflect() protoreflect.Message {
	mi := &file_TBFSMCACHENIN1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TBFSMCACHENIN1.ProtoReflect.Descriptor instead.
func (*TBFSMCACHENIN1) Descriptor() ([]byte, []int) {
	return file_TBFSMCACHENIN1_proto_rawDescGZIP(), []int{0}
}

func (x *TBFSMCACHENIN1) GetSelects() []*TBDROP {
	if x != nil {
		return x.Selects
	}
	return nil
}

func (x *TBFSMCACHENIN1) GetRerollCount() []uint32 {
	if x != nil {
		return x.RerollCount
	}
	return nil
}

func (x *TBFSMCACHENIN1) GetIsFromShop() uint32 {
	if x != nil && x.IsFromShop != nil {
		return *x.IsFromShop
	}
	return 0
}

var File_TBFSMCACHENIN1_proto protoreflect.FileDescriptor

const file_TBFSMCACHENIN1_proto_rawDesc = "" +
	"\n" +
	"\x14TBFSMCACHENIN1.proto\x12\abelfast\x1a\fTBDROP.proto\"\x80\x01\n" +
	"\x0eTBFSMCACHENIN1\x12)\n" +
	"\aselects\x18\x01 \x03(\v2\x0f.belfast.TBDROPR\aselects\x12!\n" +
	"\freroll_count\x18\x02 \x03(\rR\vrerollCount\x12 \n" +
	"\fis_from_shop\x18\x03 \x02(\rR\n" +
	"isFromShopB\fZ\n" +
	"./protobuf"

var (
	file_TBFSMCACHENIN1_proto_rawDescOnce sync.Once
	file_TBFSMCACHENIN1_proto_rawDescData []byte
)

func file_TBFSMCACHENIN1_proto_rawDescGZIP() []byte {
	file_TBFSMCACHENIN1_proto_rawDescOnce.Do(func() {
		file_TBFSMCACHENIN1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TBFSMCACHENIN1_proto_rawDesc), len(file_TBFSMCACHENIN1_proto_rawDesc)))
	})
	return file_TBFSMCACHENIN1_proto_rawDescData
}

var file_TBFSMCACHENIN1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TBFSMCACHENIN1_proto_goTypes = []any{
	(*TBFSMCACHENIN1)(nil), // 0: belfast.TBFSMCACHENIN1
	(*TBDROP)(nil),         // 1: belfast.TBDROP
}
var file_TBFSMCACHENIN1_proto_depIdxs = []int32{
	1, // 0: belfast.TBFSMCACHENIN1.selects:type_name -> belfast.TBDROP
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_TBFSMCACHENIN1_proto_init() }
func file_TBFSMCACHENIN1_proto_init() {
	if File_TBFSMCACHENIN1_proto != nil {
		return
	}
	file_TBDROP_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TBFSMCACHENIN1_proto_rawDesc), len(file_TBFSMCACHENIN1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TBFSMCACHENIN1_proto_goTypes,
		DependencyIndexes: file_TBFSMCACHENIN1_proto_depIdxs,
		MessageInfos:      file_TBFSMCACHENIN1_proto_msgTypes,
	}.Build()
	File_TBFSMCACHENIN1_proto = out.File
	file_TBFSMCACHENIN1_proto_goTypes = nil
	file_TBFSMCACHENIN1_proto_depIdxs = nil
}
