// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: TBFSMCACHEEVAL.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TBFSMCACHEEVAL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFinished    *uint32                `protobuf:"varint,1,req,name=is_finished,json=isFinished" json:"is_finished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TBFSMCACHEEVAL) Reset() {
	*x = TBFSMCACHEEVAL{}
	mi := &file_TBFSMCACHEEVAL_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TBFSMCACHEEVAL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TBFSMCACHEEVAL) ProtoMessage() {}

func (x *TBFSMCACHEEVAL) ProtoReflect() protoreflect.Message {
	mi := &file_TBFSMCACHEEVAL_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TBFSMCACHEEVAL.ProtoReflect.Descriptor instead.
func (*TBFSMCACHEEVAL) Descriptor() ([]byte, []int) {
	return file_TBFSMCACHEEVAL_proto_rawDescGZIP(), []int{0}
}

func (x *TBFSMCACHEEVAL) GetIsFinished() uint32 {
	if x != nil && x.IsFinished != nil {
		return *x.IsFinished
	}
	return 0
}

var File_TBFSMCACHEEVAL_proto protoreflect.FileDescriptor

const file_TBFSMCACHEEVAL_proto_rawDesc = "" +
	"\n" +
	"\x14TBFSMCACHEEVAL.proto\x12\abelfast\"1\n" +
	"\x0eTBFSMCACHEEVAL\x12\x1f\n" +
	"\vis_finished\x18\x01 \x02(\rR\n" +
	"isFinishedB\fZ\n" +
	"./protobuf"

var (
	file_TBFSMCACHEEVAL_proto_rawDescOnce sync.Once
	file_TBFSMCACHEEVAL_proto_rawDescData []byte
)

func file_TBFSMCACHEEVAL_proto_rawDescGZIP() []byte {
	file_TBFSMCACHEEVAL_proto_rawDescOnce.Do(func() {
		file_TBFSMCACHEEVAL_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TBFSMCACHEEVAL_proto_rawDesc), len(file_TBFSMCACHEEVAL_proto_rawDesc)))
	})
	return file_TBFSMCACHEEVAL_proto_rawDescData
}

var file_TBFSMCACHEEVAL_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TBFSMCACHEEVAL_proto_goTypes = []any{
	(*TBFSMCACHEEVAL)(nil), // 0: belfast.TBFSMCACHEEVAL
}
var file_TBFSMCACHEEVAL_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TBFSMCACHEEVAL_proto_init() }
func file_TBFSMCACHEEVAL_proto_init() {
	if File_TBFSMCACHEEVAL_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TBFSMCACHEEVAL_proto_rawDesc), len(file_TBFSMCACHEEVAL_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TBFSMCACHEEVAL_proto_goTypes,
		DependencyIndexes: file_TBFSMCACHEEVAL_proto_depIdxs,
		MessageInfos:      file_TBFSMCACHEEVAL_proto_msgTypes,
	}.Build()
	File_TBFSMCACHEEVAL_proto = out.File
	file_TBFSMCACHEEVAL_proto_goTypes = nil
	file_TBFSMCACHEEVAL_proto_depIdxs = nil
}
