// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: TBFSMCACHE_KR.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TBFSMCACHE_KR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CachePlan     []*TBFSMCACHEPLAN      `protobuf:"bytes,1,rep,name=cache_plan,json=cachePlan" json:"cache_plan,omitempty"`
	CacheTalent   []*TBFSMCACHETALENT    `protobuf:"bytes,2,rep,name=cache_talent,json=cacheTalent" json:"cache_talent,omitempty"`
	CacheSite     []*TBFSMCACHESITE_KR   `protobuf:"bytes,3,rep,name=cache_site,json=cacheSite" json:"cache_site,omitempty"`
	CacheChat     []*TBFSMCACHECHAT      `protobuf:"bytes,4,rep,name=cache_chat,json=cacheChat" json:"cache_chat,omitempty"`
	CacheEnd      []*TBFSMCACHEEND       `protobuf:"bytes,5,rep,name=cache_end,json=cacheEnd" json:"cache_end,omitempty"`
	CacheMind     []*TBFSMCACHEMIND      `protobuf:"bytes,6,rep,name=cache_mind,json=cacheMind" json:"cache_mind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TBFSMCACHE_KR) Reset() {
	*x = TBFSMCACHE_KR{}
	mi := &file_TBFSMCACHE_KR_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TBFSMCACHE_KR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TBFSMCACHE_KR) ProtoMessage() {}

func (x *TBFSMCACHE_KR) ProtoReflect() protoreflect.Message {
	mi := &file_TBFSMCACHE_KR_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TBFSMCACHE_KR.ProtoReflect.Descriptor instead.
func (*TBFSMCACHE_KR) Descriptor() ([]byte, []int) {
	return file_TBFSMCACHE_KR_proto_rawDescGZIP(), []int{0}
}

func (x *TBFSMCACHE_KR) GetCachePlan() []*TBFSMCACHEPLAN {
	if x != nil {
		return x.CachePlan
	}
	return nil
}

func (x *TBFSMCACHE_KR) GetCacheTalent() []*TBFSMCACHETALENT {
	if x != nil {
		return x.CacheTalent
	}
	return nil
}

func (x *TBFSMCACHE_KR) GetCacheSite() []*TBFSMCACHESITE_KR {
	if x != nil {
		return x.CacheSite
	}
	return nil
}

func (x *TBFSMCACHE_KR) GetCacheChat() []*TBFSMCACHECHAT {
	if x != nil {
		return x.CacheChat
	}
	return nil
}

func (x *TBFSMCACHE_KR) GetCacheEnd() []*TBFSMCACHEEND {
	if x != nil {
		return x.CacheEnd
	}
	return nil
}

func (x *TBFSMCACHE_KR) GetCacheMind() []*TBFSMCACHEMIND {
	if x != nil {
		return x.CacheMind
	}
	return nil
}

var File_TBFSMCACHE_KR_proto protoreflect.FileDescriptor

const file_TBFSMCACHE_KR_proto_rawDesc = "" +
	"\n" +
	"\x13TBFSMCACHE_KR.proto\x12\abelfast\x1a\x14TBFSMCACHECHAT.proto\x1a\x13TBFSMCACHEEND.proto\x1a\x14TBFSMCACHEMIND.proto\x1a\x14TBFSMCACHEPLAN.proto\x1a\x17TBFSMCACHESITE_KR.proto\x1a\x16TBFSMCACHETALENT.proto\"\xe5\x02\n" +
	"\rTBFSMCACHE_KR\x126\n" +
	"\n" +
	"cache_plan\x18\x01 \x03(\v2\x17.belfast.TBFSMCACHEPLANR\tcachePlan\x12<\n" +
	"\fcache_talent\x18\x02 \x03(\v2\x19.belfast.TBFSMCACHETALENTR\vcacheTalent\x129\n" +
	"\n" +
	"cache_site\x18\x03 \x03(\v2\x1a.belfast.TBFSMCACHESITE_KRR\tcacheSite\x126\n" +
	"\n" +
	"cache_chat\x18\x04 \x03(\v2\x17.belfast.TBFSMCACHECHATR\tcacheChat\x123\n" +
	"\tcache_end\x18\x05 \x03(\v2\x16.belfast.TBFSMCACHEENDR\bcacheEnd\x126\n" +
	"\n" +
	"cache_mind\x18\x06 \x03(\v2\x17.belfast.TBFSMCACHEMINDR\tcacheMindB\fZ\n" +
	"./protobuf"

var (
	file_TBFSMCACHE_KR_proto_rawDescOnce sync.Once
	file_TBFSMCACHE_KR_proto_rawDescData []byte
)

func file_TBFSMCACHE_KR_proto_rawDescGZIP() []byte {
	file_TBFSMCACHE_KR_proto_rawDescOnce.Do(func() {
		file_TBFSMCACHE_KR_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TBFSMCACHE_KR_proto_rawDesc), len(file_TBFSMCACHE_KR_proto_rawDesc)))
	})
	return file_TBFSMCACHE_KR_proto_rawDescData
}

var file_TBFSMCACHE_KR_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TBFSMCACHE_KR_proto_goTypes = []any{
	(*TBFSMCACHE_KR)(nil),     // 0: belfast.TBFSMCACHE_KR
	(*TBFSMCACHEPLAN)(nil),    // 1: belfast.TBFSMCACHEPLAN
	(*TBFSMCACHETALENT)(nil),  // 2: belfast.TBFSMCACHETALENT
	(*TBFSMCACHESITE_KR)(nil), // 3: belfast.TBFSMCACHESITE_KR
	(*TBFSMCACHECHAT)(nil),    // 4: belfast.TBFSMCACHECHAT
	(*TBFSMCACHEEND)(nil),     // 5: belfast.TBFSMCACHEEND
	(*TBFSMCACHEMIND)(nil),    // 6: belfast.TBFSMCACHEMIND
}
var file_TBFSMCACHE_KR_proto_depIdxs = []int32{
	1, // 0: belfast.TBFSMCACHE_KR.cache_plan:type_name -> belfast.TBFSMCACHEPLAN
	2, // 1: belfast.TBFSMCACHE_KR.cache_talent:type_name -> belfast.TBFSMCACHETALENT
	3, // 2: belfast.TBFSMCACHE_KR.cache_site:type_name -> belfast.TBFSMCACHESITE_KR
	4, // 3: belfast.TBFSMCACHE_KR.cache_chat:type_name -> belfast.TBFSMCACHECHAT
	5, // 4: belfast.TBFSMCACHE_KR.cache_end:type_name -> belfast.TBFSMCACHEEND
	6, // 5: belfast.TBFSMCACHE_KR.cache_mind:type_name -> belfast.TBFSMCACHEMIND
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_TBFSMCACHE_KR_proto_init() }
func file_TBFSMCACHE_KR_proto_init() {
	if File_TBFSMCACHE_KR_proto != nil {
		return
	}
	file_TBFSMCACHECHAT_proto_init()
	file_TBFSMCACHEEND_proto_init()
	file_TBFSMCACHEMIND_proto_init()
	file_TBFSMCACHEPLAN_proto_init()
	file_TBFSMCACHESITE_KR_proto_init()
	file_TBFSMCACHETALENT_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TBFSMCACHE_KR_proto_rawDesc), len(file_TBFSMCACHE_KR_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TBFSMCACHE_KR_proto_goTypes,
		DependencyIndexes: file_TBFSMCACHE_KR_proto_depIdxs,
		MessageInfos:      file_TBFSMCACHE_KR_proto_msgTypes,
	}.Build()
	File_TBFSMCACHE_KR_proto = out.File
	file_TBFSMCACHE_KR_proto_goTypes = nil
	file_TBFSMCACHE_KR_proto_depIdxs = nil
}
