// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: TBINFO_KR.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TBINFO_KR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Fsm           *TBFSM_KR              `protobuf:"bytes,2,req,name=fsm" json:"fsm,omitempty"`
	Round         *TBROUND_KR            `protobuf:"bytes,3,req,name=round" json:"round,omitempty"`
	Res           *TBRES                 `protobuf:"bytes,4,req,name=res" json:"res,omitempty"`
	Talent        *TBTALENT              `protobuf:"bytes,5,req,name=talent" json:"talent,omitempty"`
	Plan          *TBPLAN                `protobuf:"bytes,6,req,name=plan" json:"plan,omitempty"`
	Site          *TBSITE                `protobuf:"bytes,7,req,name=site" json:"site,omitempty"`
	Evaluations   []*KVDATA              `protobuf:"bytes,8,rep,name=evaluations" json:"evaluations,omitempty"`
	Name          *string                `protobuf:"bytes,9,req,name=name" json:"name,omitempty"`
	FavorLv       *uint32                `protobuf:"varint,10,req,name=favor_lv,json=favorLv" json:"favor_lv,omitempty"`
	Benefit       *TBBENEFIT_KR          `protobuf:"bytes,11,req,name=benefit" json:"benefit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TBINFO_KR) Reset() {
	*x = TBINFO_KR{}
	mi := &file_TBINFO_KR_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TBINFO_KR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TBINFO_KR) ProtoMessage() {}

func (x *TBINFO_KR) ProtoReflect() protoreflect.Message {
	mi := &file_TBINFO_KR_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TBINFO_KR.ProtoReflect.Descriptor instead.
func (*TBINFO_KR) Descriptor() ([]byte, []int) {
	return file_TBINFO_KR_proto_rawDescGZIP(), []int{0}
}

func (x *TBINFO_KR) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TBINFO_KR) GetFsm() *TBFSM_KR {
	if x != nil {
		return x.Fsm
	}
	return nil
}

func (x *TBINFO_KR) GetRound() *TBROUND_KR {
	if x != nil {
		return x.Round
	}
	return nil
}

func (x *TBINFO_KR) GetRes() *TBRES {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *TBINFO_KR) GetTalent() *TBTALENT {
	if x != nil {
		return x.Talent
	}
	return nil
}

func (x *TBINFO_KR) GetPlan() *TBPLAN {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *TBINFO_KR) GetSite() *TBSITE {
	if x != nil {
		return x.Site
	}
	return nil
}

func (x *TBINFO_KR) GetEvaluations() []*KVDATA {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

func (x *TBINFO_KR) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TBINFO_KR) GetFavorLv() uint32 {
	if x != nil && x.FavorLv != nil {
		return *x.FavorLv
	}
	return 0
}

func (x *TBINFO_KR) GetBenefit() *TBBENEFIT_KR {
	if x != nil {
		return x.Benefit
	}
	return nil
}

var File_TBINFO_KR_proto protoreflect.FileDescriptor

const file_TBINFO_KR_proto_rawDesc = "" +
	"\n" +
	"\x0fTBINFO_KR.proto\x12\abelfast\x1a\fKVDATA.proto\x1a\x12TBBENEFIT_KR.proto\x1a\x0eTBFSM_KR.proto\x1a\fTBPLAN.proto\x1a\vTBRES.proto\x1a\x10TBROUND_KR.proto\x1a\fTBSITE.proto\x1a\x0eTBTALENT.proto\"\x95\x03\n" +
	"\tTBINFO_KR\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12#\n" +
	"\x03fsm\x18\x02 \x02(\v2\x11.belfast.TBFSM_KRR\x03fsm\x12)\n" +
	"\x05round\x18\x03 \x02(\v2\x13.belfast.TBROUND_KRR\x05round\x12 \n" +
	"\x03res\x18\x04 \x02(\v2\x0e.belfast.TBRESR\x03res\x12)\n" +
	"\x06talent\x18\x05 \x02(\v2\x11.belfast.TBTALENTR\x06talent\x12#\n" +
	"\x04plan\x18\x06 \x02(\v2\x0f.belfast.TBPLANR\x04plan\x12#\n" +
	"\x04site\x18\a \x02(\v2\x0f.belfast.TBSITER\x04site\x121\n" +
	"\vevaluations\x18\b \x03(\v2\x0f.belfast.KVDATAR\vevaluations\x12\x12\n" +
	"\x04name\x18\t \x02(\tR\x04name\x12\x19\n" +
	"\bfavor_lv\x18\n" +
	" \x02(\rR\afavorLv\x12/\n" +
	"\abenefit\x18\v \x02(\v2\x15.belfast.TBBENEFIT_KRR\abenefitB\fZ\n" +
	"./protobuf"

var (
	file_TBINFO_KR_proto_rawDescOnce sync.Once
	file_TBINFO_KR_proto_rawDescData []byte
)

func file_TBINFO_KR_proto_rawDescGZIP() []byte {
	file_TBINFO_KR_proto_rawDescOnce.Do(func() {
		file_TBINFO_KR_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TBINFO_KR_proto_rawDesc), len(file_TBINFO_KR_proto_rawDesc)))
	})
	return file_TBINFO_KR_proto_rawDescData
}

var file_TBINFO_KR_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TBINFO_KR_proto_goTypes = []any{
	(*TBINFO_KR)(nil),    // 0: belfast.TBINFO_KR
	(*TBFSM_KR)(nil),     // 1: belfast.TBFSM_KR
	(*TBROUND_KR)(nil),   // 2: belfast.TBROUND_KR
	(*TBRES)(nil),        // 3: belfast.TBRES
	(*TBTALENT)(nil),     // 4: belfast.TBTALENT
	(*TBPLAN)(nil),       // 5: belfast.TBPLAN
	(*TBSITE)(nil),       // 6: belfast.TBSITE
	(*KVDATA)(nil),       // 7: belfast.KVDATA
	(*TBBENEFIT_KR)(nil), // 8: belfast.TBBENEFIT_KR
}
var file_TBINFO_KR_proto_depIdxs = []int32{
	1, // 0: belfast.TBINFO_KR.fsm:type_name -> belfast.TBFSM_KR
	2, // 1: belfast.TBINFO_KR.round:type_name -> belfast.TBROUND_KR
	3, // 2: belfast.TBINFO_KR.res:type_name -> belfast.TBRES
	4, // 3: belfast.TBINFO_KR.talent:type_name -> belfast.TBTALENT
	5, // 4: belfast.TBINFO_KR.plan:type_name -> belfast.TBPLAN
	6, // 5: belfast.TBINFO_KR.site:type_name -> belfast.TBSITE
	7, // 6: belfast.TBINFO_KR.evaluations:type_name -> belfast.KVDATA
	8, // 7: belfast.TBINFO_KR.benefit:type_name -> belfast.TBBENEFIT_KR
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_TBINFO_KR_proto_init() }
func file_TBINFO_KR_proto_init() {
	if File_TBINFO_KR_proto != nil {
		return
	}
	file_KVDATA_proto_init()
	file_TBBENEFIT_KR_proto_init()
	file_TBFSM_KR_proto_init()
	file_TBPLAN_proto_init()
	file_TBRES_proto_init()
	file_TBROUND_KR_proto_init()
	file_TBSITE_proto_init()
	file_TBTALENT_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TBINFO_KR_proto_rawDesc), len(file_TBINFO_KR_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TBINFO_KR_proto_goTypes,
		DependencyIndexes: file_TBINFO_KR_proto_depIdxs,
		MessageInfos:      file_TBINFO_KR_proto_msgTypes,
	}.Build()
	File_TBINFO_KR_proto = out.File
	file_TBINFO_KR_proto_goTypes = nil
	file_TBINFO_KR_proto_depIdxs = nil
}
